"""Adiciona campos para estrutura HTML das disciplinas

Revision ID: 2d13fad43e06
Revises: f627da294d54
Create Date: 2025-05-26 19:19:15.933616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d13fad43e06'
down_revision = 'f627da294d54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplina', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aulas', sa.PickleType(), nullable=True))
        batch_op.add_column(sa.Column('planejamento', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('flashcards', sa.PickleType(), nullable=True))
        batch_op.add_column(sa.Column('resumos', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('apresentacao', sa.Text(), nullable=True))
        batch_op.alter_column('categoria',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplina', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('categoria',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('apresentacao')
        batch_op.drop_column('resumos')
        batch_op.drop_column('flashcards')
        batch_op.drop_column('planejamento')
        batch_op.drop_column('aulas')

    # ### end Alembic commands ###
