"""Inicial

Revision ID: f627da294d54
Revises: 
Create Date: 2025-05-23 11:42:40.938931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f627da294d54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_disciplina')
    with op.batch_alter_table('disciplina', schema=None) as batch_op:
        batch_op.alter_column('categoria',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('tipo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('link',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplina', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('categoria',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    op.create_table('_alembic_tmp_disciplina',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=50), nullable=True),
    sa.Column('ordem', sa.INTEGER(), nullable=True),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('link', sa.VARCHAR(length=255), nullable=True),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
